// Code generated by "stringer -type=Language"; DO NOT EDIT

package template

import "fmt"

const _Language_name = "TypescriptFlowElm"

var _Language_index = [...]uint8{0, 10, 14, 17}

func (i Language) String() string {
	if i < 0 || i >= Language(len(_Language_index)-1) {
		return fmt.Sprintf("Language(%d)", i)
	}
	return _Language_name[_Language_index[i]:_Language_index[i+1]]
}
