// @flow
// Automatically generated by typewriter. Do not edit.
// http://www.github.com/natdm/typewriter


// Embedded is testing an embedded struct
export type Embedded = { 
	created_at: Date// manually overriding field with a name
}

// Event ..
export type Event = { 
	name: string
}

// Example represents most of what TW can do.
export type Example = { 
	basic: string, // basic types
	maps: { [key: string]: Event }, // map types
	slices_too: Array<Event>, // slices
	event_pointer: ?Event, // pointers
	created_at: Date// manually overriding field with a name
}

// Time ..
export type Time = Date
